### PR TITLE
Updated fr (French) translation

### PR DESCRIPTION
**Pull request by arnaud-jacquemin**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by gsantner** [comment]
Seems like your repository has somehow old commits. Im gonna merge this manually. Please deleted your github repo and stringlate repo on your phone, that will resolve all problems for sure then.

**Comment by gsantner** [comment]
yep, you did, but not a big problem. Dont find a option to change branch at stringlate currently, dont know how it happened, sorry

**Comment by arnaud-jacquemin** [comment]
I think I've fixed the mess.... My branch should have a "ready to merge" version now.

**Comment by gsantner** [comment]
thanks for your time and contribution(s)! merged

**Pull request closed without merging**
