### PR TITLE
Navslider report

### LINKED ISSUE #104: Additional options for NavSlider ; Update settings hierachy
#### General information

* **App version:**  0.1.6-next
* **App source:** HEAD

#### Steps to reproduce

1. Open NavSlider
2. No Option for Reports

#### Expected result
**What is the expected output?** 
* An Option for "Reports"
* Suburl for `PODADDRESS/reports`
* Available only to Admins/Mods
* Divide navslider visibility options into user, general and admin categeories
    * Personal (Profile, Contacts, ....)
    * General (Exit app, About)
    * Admin (Reports / Statistics (dunno if available :) ) 

**What do you see instead?**
No such option

### PR DESCRIPTION
**Pull request by vanitasvitae**
Fixes #104

### CODE REVIEW

**Comment by gsantner** [comment]
we should create a new PR after releasing v0.2.0. This one contains another commit

**Comment by vanitasvitae** [comment]
Should I rebase this PR on 0.2.0?

**Comment by gsantner** [comment]
Yeah, but conquering the visibility options (described in issue) is my target.

e.g. Personal (Profile, Contacts, ....)  |  General (Exit app, About) | Admin (Reports / Statistics (dunno if available :) )

**Comment by vanitasvitae** [comment]
The PR already divided the entries into general and admin.

**Pull request closed without merging**
