### PR TITLE
Added icons to notification dropdown

### LINKED ISSUE #150: Replace notifications dropdown menu with drop down icon bar
#### General information

* **Android Device:**
* **Android API Version:** 
* **App version:**
* **App source:**
* **Pod version:**

#### Steps to reproduce

1. Click the notification bell with drop down menu enabled

#### Expected result
**What is the expected output?** 
A nice toolbar with different icons representing different notification types appears below the top toolbar

**What do you see instead?**
The textual drop down menu appears

As requested by ravenbird

### PR DESCRIPTION
**Pull request by vanitasvitae**
Fixes #150 
screenshot_20170308-003743

### CODE REVIEW

**Comment by gsantner** [comment]
Please use vector drawables (these icons are all from material icons right?)
The icons itself are right chosen, great that it works :). We can send this screen on d\* to the origin post

**Comment by vanitasvitae** [comment]
@gsantner Ah yes you're right.

**Comment by gsantner** [comment]
Just as a note: Everything  vector drawable `*_48px_black` from material icons is fine. I maybe replace all of those currently in `/res/drawable` soon with `_48px_black`. There are currently some unneded duplicates

**Comment by vanitasvitae** [comment]
Changes are in master

**Pull request closed without merging**
