### PR TITLE
Wipe settings (Fixes #93)

### LINKED ISSUE #93: Add debug feature that wipes all settings
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

It would be nice to have a feature in the app that clears all settings (app and pods).
We could forward users with strange issues to that option instead of figuring out, how the user can delete that settings manually.

### PR DESCRIPTION
**Pull request by vanitasvitae**

### CODE REVIEW

**Comment by gsantner** [comment]
Is this ready to merge?
I would rebase this when I'm free, because of the changes on master yesterday

**Comment by vanitasvitae** [comment]
I already merged master into this. I think this is ready though

**Comment by vanitasvitae** [comment]
I found an easier way to accomplish this. I'll quickly rework this :)

**Comment by gsantner** [comment]
Oh okay
- oh okay, again :D

**Comment by vanitasvitae** [comment]
Why does it also squash your changes from yesterday?
I think this must be manually merged into master because there are some conflicts (easy to fix)

**Pull request merged**
