### PR TITLE
Fixup: markdown image links

### PR DESCRIPTION
**Pull request by jayaddison**
Updates the screenshot URLs in `README.md`, and removes the legacy `SCREENSHOTS.md`.

### CODE REVIEW

**Comment by gsantner** [comment]
I havent encountered SCREENSHOTS.md anywhere yet. Is there any specific client/app/frontend which makes special use of it.

If not, I don't want to duplicate the README.

**Comment by gsantner** [comment]
Is there any specific client/app/frontend which makes special use of SCREENSHOTS.md?

If not, I don't want to duplicate the README anymore :D.

**Comment by jayaddison** [comment]
> Is there any specific client/app/frontend which makes special use of SCREENSHOTS.md?
> 
> If not, I don't want to duplicate the README anymore :D.

Nothing within the app certainly - doing a little more searching around.  Hopefully it's fine to remove!

**Comment by jayaddison** [comment]
Removed in the branch, although I'm kinda wondering whether it might be used in a build / packaging process somewhere.

**Comment by jayaddison** [comment]
Learning a bit about the f-droid app store today - it looks like the current screenshots for the app are hosted by their (self-maintained) metadata repository, although they were likely sourced from here in the past.

`SCREENSHOTS.md` doesn't seem to be in the `fastlane` or `gradle-play-publisher` docs mentioned by the [app metadata FAQs](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-change-the-description-and-add-meta-information-like-screenshots)...

...so, maybe remove it and blame me if it goes wrong? :)

**Comment by gsantner** [comment]
I don't know about any use of it at fdroid or fastlane either

**Pull request merged**
