### PR TITLE
pull to refresh page

### PR DESCRIPTION
**Pull request by massimilianoLe**

### CODE REVIEW

**Comment by gsantner** [comment]
we already had this and were not so happy with it in combination with autohide toolbars.

**Comment by massimilianoLe** [comment]
Should i undo it?

**Comment by gsantner** [comment]
No, as not merged nothing changed on the repo yet :)

**Comment by Flaburgan** [comment]
What was the problem exactly?

**Comment by massimilianoLe** [comment]
For me, none. I tested it and seemed ok. Maybe you can try it again?

**Pull request merged**
