### PR TITLE
Add "Followed tags" listing

### PR DESCRIPTION
**Pull request by di72nn**
Add "Followed tags" listing analogous to "Aspects" listing.

### CODE REVIEW

**Comment by gsantner** [comment]
Thanks for your work!
Seems good, I looked on the code also, didnt saw any problems.
I am currently on vacation w/o access to dev environment to try it. I will come back to this PR next beginning of the week.

**Comment by gsantner** [comment]
I tried it today, and it works as intended.
I found one bug: When the **Followed Tags** item gets selected (NavDrawer), the **Aspects** item cannot be selected, and the other way round.

Please pull in the latest changes from master (Fixes the BuildBot/Travis CI, all builds will fail otherwise, because there are some bugs in their code right now, which needed an workaround from outside). before fixing this.

Edit: I also removed some lines of code from creating the aspects list, and made it a little better natural to the app. (https://github.com/Diaspora-for-Android/diaspora-android/blob/6003cdfb7e5a0872edacc27595bc9118465024e7/app/src/main/java/com/github/dfa/diaspora_android/util/Helpers.java#L95)



Maybe you have also some ideas how to improve it, you can also reuse that.
It's up to you.

**Comment by di72nn** [comment]
Updated.

> I found one bug: When the Followed Tags item gets selected (NavDrawer), the Aspects item cannot be selected, and the other way round.

Fixed. Same error was discussed [here](https://stackoverflow.com/questions/4096783/android-webview-1st-loaddata-works-fine-subsequent-calls-do-not-update-disp).

**Comment by gsantner** [comment]
Thanks for your update! I am merging now.

**Pull request merged**
