### PR TITLE
Added icons to the settings

### PR DESCRIPTION
**Pull request by vanitasvitae**

### CODE REVIEW

**Comment by gsantner** [comment]
Discussion:
Some recommendations (https://material.io/icons/)

Intellihide:  zoom out map
Erweiterte Benachrichtigungen: Notifcations (like in Main-Toolbar)
Verweise auf die App: Thumb up
Chrome Custom Tabs: Open in Browser
Persönliche Einstellungen: person/person outline
Kontakte: people/people outline
Konto wechseln: Arrow back

**Comment by vanitasvitae** [comment]
Custom Tabs: I think I'd stick with the current icon, since open in custom tab describes the exact opposite of open in browser.

Im fine with the rest :+1: 

Edit: Is the size okay?
Should we tint the icons with accent/primary color or leave it black?

**Comment by vanitasvitae** [comment]
Should we tint the icons with accent/primary color or leave it black?

**Comment by gsantner** [comment]
As said, personal recommendation :D.
yeah leave it black

Could you attach screenshot of all settings & subsettings?

**Comment by gsantner** [comment]
Could you attach screenshot of all settings & subsettings?

**Comment by vanitasvitae** [comment]
screenshot_20161027-233142
screenshot_20161027-233137
screenshot_20161027-233123
screenshot_20161027-233115
screenshot_20161027-233108
screenshot_20161027-233101
screenshot_20161027-233052

**Pull request merged**
