### PR TITLE
Updated fr (French) translation

### PR DESCRIPTION
**Pull request by arnaud-jacquemin**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by arnaud-jacquemin** [comment]
Sorry, the same problem again... I was careful that the `master` branch was selected in Stringlate, but it still forked from another branch... It looks like there's a bug somewhere!
Sorry for the inconvenience!

**Comment by gsantner** [comment]
thanks for both, translating and noticing a bug

**Comment by Lonami** [comment]
@arnaud-jacquemin thanks for your effort this might be a "bug" in Stringlate's side so please forgive me if anything! ^^'

**Comment by gsantner** [comment]
how much strings did you translate totally here? just like 5 or was it pretty much everything?

**Comment by Lonami** [comment]
@arnaud-jacquemin I may try investigating more on this in a future, so currently no need to open an issue.

**Pull request closed without merging**
