### PR TITLE
Updated sc (Sardinian) translation

### PR DESCRIPTION
**Pull request by asereze**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by gsantner** [comment]
hey, you literally changed every single line and file of the project :D. easiest just fork latest state of project and copy the single file over

**Comment by asereze** [comment]
Oh, that's weird, I only used the "make a pull request" option from Stringlate. Anyway ok, I will try to change the file right now!

**Comment by gsantner** [comment]
Sorry! :D You can try todo a fresh clone (delete -> select app again), or can just export the single translation via something else than git-repo (issue, mail eg)

**Comment by gsantner** [comment]
@Lonami / @LonamiWebs

happens often that repos get PRs like this with starting from very old commit.
What do you think about having a prominent 

!!!Danger may be outdated, please refresh before starting translating again!!! (Click yes to pull and reset)

warning, when a user opens a local cloned repo and have not updated in past e.g. 7 days?

**Comment by asereze** [comment]
Oh, ok! Yes, in my opinion it's a good idea, I thought I had refreshed it recently but I'm probably wrong, a notification like that one could be really useful!

**Comment by gsantner** [comment]
No its not your fault, but we must tell this clearer and allow to make action easy

**Pull request closed without merging**
